# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ac_smoke.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(1488, 779)
        Dialog.setMinimumSize(QtCore.QSize(1488, 779))
        Dialog.setWindowTitle("")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.groupBox_hidden = QtWidgets.QGroupBox(Dialog)
        self.groupBox_hidden.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_hidden.sizePolicy().hasHeightForWidth())
        self.groupBox_hidden.setSizePolicy(sizePolicy)
        self.groupBox_hidden.setMinimumSize(QtCore.QSize(1, 1))
        self.groupBox_hidden.setMaximumSize(QtCore.QSize(0, 0))
        self.groupBox_hidden.setFlat(False)
        self.groupBox_hidden.setCheckable(False)
        self.groupBox_hidden.setObjectName("groupBox_hidden")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_hidden)
        self.gridLayout.setObjectName("gridLayout")
        self.editIP = QtWidgets.QLineEdit(self.groupBox_hidden)
        self.editIP.setMinimumSize(QtCore.QSize(0, 0))
        self.editIP.setObjectName("editIP")
        self.gridLayout.addWidget(self.editIP, 0, 0, 1, 2)
        self.editPort = QtWidgets.QLineEdit(self.groupBox_hidden)
        self.editPort.setObjectName("editPort")
        self.gridLayout.addWidget(self.editPort, 0, 2, 1, 3)
        self.editChannel = QtWidgets.QLineEdit(self.groupBox_hidden)
        self.editChannel.setObjectName("editChannel")
        self.gridLayout.addWidget(self.editChannel, 0, 5, 1, 1)
        self.editUser = QtWidgets.QLineEdit(self.groupBox_hidden)
        self.editUser.setMinimumSize(QtCore.QSize(0, 0))
        self.editUser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editUser.setObjectName("editUser")
        self.gridLayout.addWidget(self.editUser, 1, 0, 1, 2)
        self.editPwd = QtWidgets.QLineEdit(self.groupBox_hidden)
        self.editPwd.setMinimumSize(QtCore.QSize(100, 0))
        self.editPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPwd.setObjectName("editPwd")
        self.gridLayout.addWidget(self.editPwd, 1, 2, 1, 3)
        self.checkBoxCar = QtWidgets.QCheckBox(self.groupBox_hidden)
        self.checkBoxCar.setObjectName("checkBoxCar")
        self.gridLayout.addWidget(self.checkBoxCar, 2, 0, 1, 1)
        self.checkBoxSmoke = QtWidgets.QCheckBox(self.groupBox_hidden)
        self.checkBoxSmoke.setObjectName("checkBoxSmoke")
        self.gridLayout.addWidget(self.checkBoxSmoke, 2, 1, 1, 2)
        self.checkBoxSave = QtWidgets.QCheckBox(self.groupBox_hidden)
        self.checkBoxSave.setCheckable(True)
        self.checkBoxSave.setObjectName("checkBoxSave")
        self.gridLayout.addWidget(self.checkBoxSave, 2, 3, 1, 2)
        self.radioVideo = QtWidgets.QRadioButton(self.groupBox_hidden)
        self.radioVideo.setChecked(True)
        self.radioVideo.setObjectName("radioVideo")
        self.gridLayout.addWidget(self.radioVideo, 3, 0, 1, 1)
        self.radioStream = QtWidgets.QRadioButton(self.groupBox_hidden)
        self.radioStream.setObjectName("radioStream")
        self.gridLayout.addWidget(self.radioStream, 3, 1, 1, 3)
        self.tableHistory = QtWidgets.QTableView(self.groupBox_hidden)
        self.tableHistory.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableHistory.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableHistory.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableHistory.setObjectName("tableHistory")
        self.gridLayout.addWidget(self.tableHistory, 4, 0, 1, 5)
        self.editSave = QtWidgets.QLineEdit(self.groupBox_hidden)
        self.editSave.setReadOnly(False)
        self.editSave.setObjectName("editSave")
        self.gridLayout.addWidget(self.editSave, 5, 0, 1, 4)
        self.btnSave = QtWidgets.QPushButton(self.groupBox_hidden)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 5, 4, 1, 1)
        self.horizontalLayout_15.addWidget(self.groupBox_hidden)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.sliderLevel = QtWidgets.QSlider(self.groupBox)
        self.sliderLevel.setMaximum(5)
        self.sliderLevel.setPageStep(1)
        self.sliderLevel.setProperty("value", 2)
        self.sliderLevel.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLevel.setInvertedAppearance(False)
        self.sliderLevel.setInvertedControls(False)
        self.sliderLevel.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sliderLevel.setTickInterval(1)
        self.sliderLevel.setObjectName("sliderLevel")
        self.horizontalLayout_12.addWidget(self.sliderLevel)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_13.addWidget(self.line)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBoxAutoStop = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxAutoStop.setObjectName("checkBoxAutoStop")
        self.horizontalLayout_11.addWidget(self.checkBoxAutoStop)
        self.timeEditStop = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEditStop.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEditStop.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEditStop.setCalendarPopup(False)
        self.timeEditStop.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEditStop.setTime(QtCore.QTime(0, 0, 0))
        self.timeEditStop.setObjectName("timeEditStop")
        self.horizontalLayout_11.addWidget(self.timeEditStop)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBoxAutoStart = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxAutoStart.setObjectName("checkBoxAutoStart")
        self.horizontalLayout_10.addWidget(self.checkBoxAutoStart)
        self.timeEditStart = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEditStart.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEditStart.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEditStart.setCalendarPopup(False)
        self.timeEditStart.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEditStart.setTime(QtCore.QTime(0, 0, 0))
        self.timeEditStart.setObjectName("timeEditStart")
        self.horizontalLayout_10.addWidget(self.timeEditStart)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_13.addWidget(self.line_2)
        self.btnBorder = QtWidgets.QPushButton(self.groupBox)
        self.btnBorder.setObjectName("btnBorder")
        self.verticalLayout_13.addWidget(self.btnBorder)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox1 = QtWidgets.QGroupBox(Dialog)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.labelSId = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelSId.setFont(font)
        self.labelSId.setText("")
        self.labelSId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSId.setObjectName("labelSId")
        self.horizontalLayout_3.addWidget(self.labelSId)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.labelId = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelId.setFont(font)
        self.labelId.setText("")
        self.labelId.setObjectName("labelId")
        self.horizontalLayout_6.addWidget(self.labelId)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.labelTime = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTime.setFont(font)
        self.labelTime.setText("")
        self.labelTime.setObjectName("labelTime")
        self.horizontalLayout_2.addWidget(self.labelTime)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.labelRingelmann = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelRingelmann.setFont(font)
        self.labelRingelmann.setText("")
        self.labelRingelmann.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRingelmann.setObjectName("labelRingelmann")
        self.horizontalLayout_5.addWidget(self.labelRingelmann)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.labelLine = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelLine.setFont(font)
        self.labelLine.setText("")
        self.labelLine.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLine.setObjectName("labelLine")
        self.horizontalLayout_4.addWidget(self.labelLine)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.labelPlate = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPlate.setFont(font)
        self.labelPlate.setText("")
        self.labelPlate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPlate.setObjectName("labelPlate")
        self.horizontalLayout_7.addWidget(self.labelPlate)
        self.label_24 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_7.addWidget(self.label_24)
        self.labelPColor = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPColor.setFont(font)
        self.labelPColor.setText("")
        self.labelPColor.setObjectName("labelPColor")
        self.horizontalLayout_7.addWidget(self.labelPColor)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_26 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_22.addWidget(self.label_26)
        self.labelPlate_2 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPlate_2.setFont(font)
        self.labelPlate_2.setText("")
        self.labelPlate_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPlate_2.setObjectName("labelPlate_2")
        self.horizontalLayout_22.addWidget(self.labelPlate_2)
        self.label_27 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_22.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_22.addWidget(self.label_28)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.verticalLayout_6.addWidget(self.groupBox1)
        self.groupbox = QtWidgets.QGroupBox(Dialog)
        self.groupbox.setObjectName("groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.groupbox)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSortIndicatorShown(False)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableView)
        self.verticalLayout_6.addWidget(self.groupbox)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.groupbox1 = QtWidgets.QGroupBox(Dialog)
        self.groupbox1.setObjectName("groupbox1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupbox1)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelBack = QtWidgets.QLabel(self.groupbox1)
        self.labelBack.setMinimumSize(QtCore.QSize(320, 240))
        self.labelBack.setMaximumSize(QtCore.QSize(320, 240))
        self.labelBack.setFrameShape(QtWidgets.QFrame.Box)
        self.labelBack.setText("")
        self.labelBack.setObjectName("labelBack")
        self.verticalLayout_4.addWidget(self.labelBack)
        self.labelImg1 = QtWidgets.QLabel(self.groupbox1)
        self.labelImg1.setMinimumSize(QtCore.QSize(320, 240))
        self.labelImg1.setMaximumSize(QtCore.QSize(320, 240))
        self.labelImg1.setFrameShape(QtWidgets.QFrame.Box)
        self.labelImg1.setText("")
        self.labelImg1.setObjectName("labelImg1")
        self.verticalLayout_4.addWidget(self.labelImg1)
        self.labelImg2 = QtWidgets.QLabel(self.groupbox1)
        self.labelImg2.setMinimumSize(QtCore.QSize(320, 240))
        self.labelImg2.setMaximumSize(QtCore.QSize(320, 240))
        self.labelImg2.setFrameShape(QtWidgets.QFrame.Box)
        self.labelImg2.setText("")
        self.labelImg2.setObjectName("labelImg2")
        self.verticalLayout_4.addWidget(self.labelImg2)
        self.horizontalLayout.addWidget(self.groupbox1)
        self.horizontalLayout_13.addLayout(self.horizontalLayout)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupbox2 = QtWidgets.QGroupBox(Dialog)
        self.groupbox2.setObjectName("groupbox2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupbox2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnStart = QtWidgets.QPushButton(self.groupbox2)
        self.btnStart.setDefault(True)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_8.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(self.groupbox2)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_8.addWidget(self.btnStop)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.groupbox2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.editPath = QtWidgets.QLineEdit(self.groupbox2)
        self.editPath.setReadOnly(False)
        self.editPath.setObjectName("editPath")
        self.horizontalLayout_9.addWidget(self.editPath)
        self.btnOpen = QtWidgets.QPushButton(self.groupbox2)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout_9.addWidget(self.btnOpen)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addWidget(self.groupbox2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupbox3 = QtWidgets.QGroupBox(Dialog)
        self.groupbox3.setObjectName("groupbox3")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.groupbox3)
        self.horizontalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_7 = QtWidgets.QLabel(self.groupbox3)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_7.setPalette(palette)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setStyleSheet("")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setLineWidth(0)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setIndent(0)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_26.addWidget(self.label_7)
        self.label_11 = QtWidgets.QLabel(self.groupbox3)
        self.label_11.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_11.setPalette(palette)
        self.label_11.setAutoFillBackground(True)
        self.label_11.setStyleSheet("")
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setLineWidth(0)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setIndent(0)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_26.addWidget(self.label_11)
        self.label_15 = QtWidgets.QLabel(self.groupbox3)
        self.label_15.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_15.setPalette(palette)
        self.label_15.setAutoFillBackground(True)
        self.label_15.setStyleSheet("")
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_15.setLineWidth(0)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setIndent(0)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_26.addWidget(self.label_15)
        self.label_12 = QtWidgets.QLabel(self.groupbox3)
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_12.setPalette(palette)
        self.label_12.setAutoFillBackground(True)
        self.label_12.setStyleSheet("")
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_12.setLineWidth(0)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setIndent(0)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_26.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.groupbox3)
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_13.setPalette(palette)
        self.label_13.setAutoFillBackground(True)
        self.label_13.setStyleSheet("")
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_13.setLineWidth(0)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setIndent(0)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_26.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupbox3)
        self.label_14.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_14.setPalette(palette)
        self.label_14.setAutoFillBackground(True)
        self.label_14.setStyleSheet("")
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_14.setLineWidth(0)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setIndent(0)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_26.addWidget(self.label_14)
        self.verticalLayout_10.addWidget(self.groupbox3)
        self.verticalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelMain = QtWidgets.QLabel(Dialog)
        self.labelMain.setMinimumSize(QtCore.QSize(800, 600))
        self.labelMain.setMaximumSize(QtCore.QSize(800, 600))
        self.labelMain.setFrameShape(QtWidgets.QFrame.Box)
        self.labelMain.setText("")
        self.labelMain.setObjectName("labelMain")
        self.verticalLayout.addWidget(self.labelMain)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_49 = QtWidgets.QLabel(Dialog)
        self.label_49.setFrameShape(QtWidgets.QFrame.Box)
        self.label_49.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_49.setLineWidth(1)
        self.label_49.setMidLineWidth(0)
        self.label_49.setTextFormat(QtCore.Qt.AutoText)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setWordWrap(False)
        self.label_49.setOpenExternalLinks(False)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_34.addWidget(self.label_49)
        self.label_53 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_53.setPalette(palette)
        self.label_53.setAutoFillBackground(True)
        self.label_53.setFrameShape(QtWidgets.QFrame.Box)
        self.label_53.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_53.setLineWidth(1)
        self.label_53.setMidLineWidth(0)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_34.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(Dialog)
        self.label_54.setFrameShape(QtWidgets.QFrame.Box)
        self.label_54.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_54.setLineWidth(1)
        self.label_54.setMidLineWidth(0)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_34.addWidget(self.label_54)
        self.label_55 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_55.setPalette(palette)
        self.label_55.setAutoFillBackground(True)
        self.label_55.setFrameShape(QtWidgets.QFrame.Box)
        self.label_55.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_55.setLineWidth(1)
        self.label_55.setMidLineWidth(0)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_34.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(Dialog)
        self.label_56.setFrameShape(QtWidgets.QFrame.Box)
        self.label_56.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_56.setLineWidth(1)
        self.label_56.setMidLineWidth(0)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_34.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_57.setPalette(palette)
        self.label_57.setAutoFillBackground(True)
        self.label_57.setFrameShape(QtWidgets.QFrame.Box)
        self.label_57.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_57.setLineWidth(1)
        self.label_57.setMidLineWidth(0)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_34.addWidget(self.label_57)
        self.label_58 = QtWidgets.QLabel(Dialog)
        self.label_58.setFrameShape(QtWidgets.QFrame.Box)
        self.label_58.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_58.setLineWidth(1)
        self.label_58.setMidLineWidth(0)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_34.addWidget(self.label_58)
        self.label_59 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_59.setPalette(palette)
        self.label_59.setAutoFillBackground(True)
        self.label_59.setFrameShape(QtWidgets.QFrame.Box)
        self.label_59.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_59.setLineWidth(1)
        self.label_59.setMidLineWidth(0)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_34.addWidget(self.label_59)
        self.label_60 = QtWidgets.QLabel(Dialog)
        self.label_60.setFrameShape(QtWidgets.QFrame.Box)
        self.label_60.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_60.setLineWidth(1)
        self.label_60.setMidLineWidth(0)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_34.addWidget(self.label_60)
        self.label_61 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_61.setPalette(palette)
        self.label_61.setAutoFillBackground(True)
        self.label_61.setFrameShape(QtWidgets.QFrame.Box)
        self.label_61.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_61.setLineWidth(1)
        self.label_61.setMidLineWidth(0)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_34.addWidget(self.label_61)
        self.label_62 = QtWidgets.QLabel(Dialog)
        self.label_62.setFrameShape(QtWidgets.QFrame.Box)
        self.label_62.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_62.setLineWidth(1)
        self.label_62.setMidLineWidth(0)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_34.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_63.setPalette(palette)
        self.label_63.setAutoFillBackground(True)
        self.label_63.setFrameShape(QtWidgets.QFrame.Box)
        self.label_63.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_63.setLineWidth(1)
        self.label_63.setMidLineWidth(0)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_34.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(Dialog)
        self.label_64.setFrameShape(QtWidgets.QFrame.Box)
        self.label_64.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_64.setLineWidth(1)
        self.label_64.setMidLineWidth(0)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_34.addWidget(self.label_64)
        self.label_65 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_65.setPalette(palette)
        self.label_65.setAutoFillBackground(True)
        self.label_65.setFrameShape(QtWidgets.QFrame.Box)
        self.label_65.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_65.setLineWidth(1)
        self.label_65.setMidLineWidth(0)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_34.addWidget(self.label_65)
        self.label_66 = QtWidgets.QLabel(Dialog)
        self.label_66.setFrameShape(QtWidgets.QFrame.Box)
        self.label_66.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_66.setLineWidth(1)
        self.label_66.setMidLineWidth(0)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_34.addWidget(self.label_66)
        self.label_67 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_67.setPalette(palette)
        self.label_67.setAutoFillBackground(True)
        self.label_67.setFrameShape(QtWidgets.QFrame.Box)
        self.label_67.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_67.setLineWidth(1)
        self.label_67.setMidLineWidth(0)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_34.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(Dialog)
        self.label_68.setFrameShape(QtWidgets.QFrame.Box)
        self.label_68.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_68.setLineWidth(1)
        self.label_68.setMidLineWidth(0)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_34.addWidget(self.label_68)
        self.label_69 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_69.setPalette(palette)
        self.label_69.setAutoFillBackground(True)
        self.label_69.setFrameShape(QtWidgets.QFrame.Box)
        self.label_69.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_69.setLineWidth(1)
        self.label_69.setMidLineWidth(0)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_34.addWidget(self.label_69)
        self.label_70 = QtWidgets.QLabel(Dialog)
        self.label_70.setFrameShape(QtWidgets.QFrame.Box)
        self.label_70.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_70.setLineWidth(1)
        self.label_70.setMidLineWidth(0)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_34.addWidget(self.label_70)
        self.label_71 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 224, 224))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_71.setPalette(palette)
        self.label_71.setAutoFillBackground(True)
        self.label_71.setFrameShape(QtWidgets.QFrame.Box)
        self.label_71.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_71.setLineWidth(1)
        self.label_71.setMidLineWidth(0)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_34.addWidget(self.label_71)
        self.verticalLayout.addLayout(self.horizontalLayout_34)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.horizontalLayout_13.addLayout(self.verticalLayout_8)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_13)
        self.groupBox_hidden.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.editIP, self.editPort)
        Dialog.setTabOrder(self.editPort, self.editChannel)
        Dialog.setTabOrder(self.editChannel, self.editUser)
        Dialog.setTabOrder(self.editUser, self.editPwd)
        Dialog.setTabOrder(self.editPwd, self.editPath)
        Dialog.setTabOrder(self.editPath, self.btnOpen)
        Dialog.setTabOrder(self.btnOpen, self.radioVideo)
        Dialog.setTabOrder(self.radioVideo, self.radioStream)
        Dialog.setTabOrder(self.radioStream, self.btnStart)
        Dialog.setTabOrder(self.btnStart, self.btnStop)
        Dialog.setTabOrder(self.btnStop, self.checkBoxCar)
        Dialog.setTabOrder(self.checkBoxCar, self.checkBoxSmoke)
        Dialog.setTabOrder(self.checkBoxSmoke, self.checkBoxSave)
        Dialog.setTabOrder(self.checkBoxSave, self.sliderLevel)
        Dialog.setTabOrder(self.sliderLevel, self.checkBoxAutoStart)
        Dialog.setTabOrder(self.checkBoxAutoStart, self.timeEditStart)
        Dialog.setTabOrder(self.timeEditStart, self.checkBoxAutoStop)
        Dialog.setTabOrder(self.checkBoxAutoStop, self.timeEditStop)
        Dialog.setTabOrder(self.timeEditStop, self.editSave)
        Dialog.setTabOrder(self.editSave, self.btnSave)
        Dialog.setTabOrder(self.btnSave, self.tableView)
        Dialog.setTabOrder(self.tableView, self.tableHistory)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.checkBoxCar.setText(_translate("Dialog", "标出汽车"))
        self.checkBoxSmoke.setText(_translate("Dialog", "标出黑烟"))
        self.checkBoxSave.setText(_translate("Dialog", "保存黑烟视频"))
        self.radioVideo.setText(_translate("Dialog", "视频模式"))
        self.radioStream.setText(_translate("Dialog", "视频流模式"))
        self.btnSave.setText(_translate("Dialog", "打开..."))
        self.groupBox.setTitle(_translate("Dialog", "设置"))
        self.label_2.setText(_translate("Dialog", "林格曼阈值 0"))
        self.label_23.setText(_translate("Dialog", "5"))
        self.checkBoxAutoStop.setText(_translate("Dialog", "自动停止时间"))
        self.timeEditStop.setDisplayFormat(_translate("Dialog", "HH:mm"))
        self.checkBoxAutoStart.setText(_translate("Dialog", "自动开始时间"))
        self.timeEditStart.setDisplayFormat(_translate("Dialog", "HH:mm"))
        self.btnBorder.setText(_translate("Dialog", "车道设置..."))
        self.groupBox1.setTitle(_translate("Dialog", "记录信息"))
        self.label_3.setText(_translate("Dialog", "点位编号"))
        self.label_4.setText(_translate("Dialog", "检测编号"))
        self.label_6.setText(_translate("Dialog", "检测时间"))
        self.label_10.setText(_translate("Dialog", "林格曼"))
        self.label_8.setText(_translate("Dialog", "车道号"))
        self.label_9.setText(_translate("Dialog", "车牌"))
        self.label_24.setText(_translate("Dialog", "车牌颜色"))
        self.label_26.setText(_translate("Dialog", "车型"))
        self.label_27.setText(_translate("Dialog", "车身颜色"))
        self.groupbox.setTitle(_translate("Dialog", "检测结果"))
        self.groupbox1.setTitle(_translate("Dialog", "检测结果"))
        self.groupbox2.setTitle(_translate("Dialog", "检测控制"))
        self.btnStart.setText(_translate("Dialog", "开始"))
        self.btnStop.setText(_translate("Dialog", "停止"))
        self.label_20.setText(_translate("Dialog", "选择视频"))
        self.btnOpen.setText(_translate("Dialog", "打开..."))
        self.groupbox3.setTitle(_translate("Dialog", "林格曼黑度比色卡"))
        self.label_7.setText(_translate("Dialog", "0"))
        self.label_11.setText(_translate("Dialog", "1"))
        self.label_15.setText(_translate("Dialog", "2"))
        self.label_12.setText(_translate("Dialog", "3"))
        self.label_13.setText(_translate("Dialog", "4"))
        self.label_14.setText(_translate("Dialog", "5"))
        self.label_49.setText(_translate("Dialog", "0"))
        self.label_53.setText(_translate("Dialog", "5"))
        self.label_54.setText(_translate("Dialog", "10"))
        self.label_55.setText(_translate("Dialog", "15"))
        self.label_56.setText(_translate("Dialog", "20"))
        self.label_57.setText(_translate("Dialog", "25"))
        self.label_58.setText(_translate("Dialog", "30"))
        self.label_59.setText(_translate("Dialog", "35"))
        self.label_60.setText(_translate("Dialog", "40"))
        self.label_61.setText(_translate("Dialog", "45"))
        self.label_62.setText(_translate("Dialog", "50"))
        self.label_63.setText(_translate("Dialog", "55"))
        self.label_64.setText(_translate("Dialog", "60"))
        self.label_65.setText(_translate("Dialog", "65"))
        self.label_66.setText(_translate("Dialog", "70"))
        self.label_67.setText(_translate("Dialog", "75"))
        self.label_68.setText(_translate("Dialog", "80"))
        self.label_69.setText(_translate("Dialog", "85"))
        self.label_70.setText(_translate("Dialog", "90"))
        self.label_71.setText(_translate("Dialog", "95"))

