# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 714)
        MainWindow.setMinimumSize(QtCore.QSize(1043, 714))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tv_cfg = QtWidgets.QTableView(self.groupBox)
        self.tv_cfg.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tv_cfg.setAlternatingRowColors(True)
        self.tv_cfg.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tv_cfg.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tv_cfg.setObjectName("tv_cfg")
        self.verticalLayout.addWidget(self.tv_cfg)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_start_all = QtWidgets.QPushButton(self.groupBox)
        self.btn_start_all.setObjectName("btn_start_all")
        self.horizontalLayout.addWidget(self.btn_start_all)
        self.btn_stop_all = QtWidgets.QPushButton(self.groupBox)
        self.btn_stop_all.setObjectName("btn_stop_all")
        self.horizontalLayout.addWidget(self.btn_stop_all)
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.btn_start = QtWidgets.QPushButton(self.groupBox)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(self.groupBox)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_11.addWidget(self.groupBox)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.groupBox1 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox1)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.edit_id = QtWidgets.QLineEdit(self.groupBox1)
        self.edit_id.setObjectName("edit_id")
        self.horizontalLayout_3.addWidget(self.edit_id)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.edit_name = QtWidgets.QLineEdit(self.groupBox1)
        self.edit_name.setObjectName("edit_name")
        self.horizontalLayout_5.addWidget(self.edit_name)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_15.addWidget(self.groupBox1)
        self.groupBox2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox2.setObjectName("groupBox2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cb_start = QtWidgets.QCheckBox(self.groupBox2)
        self.cb_start.setObjectName("cb_start")
        self.horizontalLayout_12.addWidget(self.cb_start)
        self.tedit_start = QtWidgets.QTimeEdit(self.groupBox2)
        self.tedit_start.setAlignment(QtCore.Qt.AlignCenter)
        self.tedit_start.setObjectName("tedit_start")
        self.horizontalLayout_12.addWidget(self.tedit_start)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cb_stop = QtWidgets.QCheckBox(self.groupBox2)
        self.cb_stop.setObjectName("cb_stop")
        self.horizontalLayout_13.addWidget(self.cb_stop)
        self.tedit_stop = QtWidgets.QTimeEdit(self.groupBox2)
        self.tedit_stop.setAlignment(QtCore.Qt.AlignCenter)
        self.tedit_stop.setObjectName("tedit_stop")
        self.horizontalLayout_13.addWidget(self.tedit_stop)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15.addWidget(self.groupBox2)
        self.groupBox3 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox3.setObjectName("groupBox3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.groupBox3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.edit_statistics_func = QtWidgets.QLineEdit(self.groupBox3)
        self.edit_statistics_func.setObjectName("edit_statistics_func")
        self.horizontalLayout_10.addWidget(self.edit_statistics_func)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.edit_staits_interval = QtWidgets.QLineEdit(self.groupBox3)
        self.edit_staits_interval.setObjectName("edit_staits_interval")
        self.horizontalLayout_9.addWidget(self.edit_staits_interval)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_15.addWidget(self.groupBox3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox4.setObjectName("groupBox4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox4)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.edit_video = QtWidgets.QLineEdit(self.groupBox4)
        self.edit_video.setObjectName("edit_video")
        self.horizontalLayout_4.addWidget(self.edit_video)
        self.btn_video = QtWidgets.QPushButton(self.groupBox4)
        self.btn_video.setObjectName("btn_video")
        self.horizontalLayout_4.addWidget(self.btn_video)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.groupBox4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        self.edit_save = QtWidgets.QLineEdit(self.groupBox4)
        self.edit_save.setObjectName("edit_save")
        self.horizontalLayout_17.addWidget(self.edit_save)
        self.btn_save = QtWidgets.QPushButton(self.groupBox4)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_17.addWidget(self.btn_save)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16.setStretch(0, 4)
        self.horizontalLayout_16.setStretch(1, 3)
        self.verticalLayout_10.addWidget(self.groupBox4)
        self.verticalLayout_6.addLayout(self.verticalLayout_10)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.groupBox5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox5.setObjectName("groupBox5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox5)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spin_ringelmann = QtWidgets.QSpinBox(self.groupBox5)
        self.spin_ringelmann.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_ringelmann.setMaximum(5)
        self.spin_ringelmann.setProperty("value", 2)
        self.spin_ringelmann.setObjectName("spin_ringelmann")
        self.horizontalLayout_6.addWidget(self.spin_ringelmann)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.groupBox5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.edit_func = QtWidgets.QLineEdit(self.groupBox5)
        self.edit_func.setObjectName("edit_func")
        self.horizontalLayout_7.addWidget(self.edit_func)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_14.addWidget(self.groupBox5)
        self.groupBox6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox6.setObjectName("groupBox6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_border = QtWidgets.QPushButton(self.groupBox6)
        self.btn_border.setObjectName("btn_border")
        self.horizontalLayout_8.addWidget(self.btn_border)
        self.horizontalLayout_14.addWidget(self.groupBox6)
        self.groupBox7 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox7.setObjectName("groupBox7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_update = QtWidgets.QPushButton(self.groupBox7)
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout_2.addWidget(self.btn_update)
        self.btn_add = QtWidgets.QPushButton(self.groupBox7)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_2.addWidget(self.btn_add)
        self.btn_delete = QtWidgets.QPushButton(self.groupBox7)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_2.addWidget(self.btn_delete)
        self.horizontalLayout_14.addWidget(self.groupBox7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_log = QtWidgets.QTextBrowser(self.groupBox_2)
        self.text_log.setObjectName("text_log")
        self.verticalLayout_2.addWidget(self.text_log)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "配置列表"))
        self.btn_start_all.setText(_translate("MainWindow", "全部开始"))
        self.btn_stop_all.setText(_translate("MainWindow", "全部停止"))
        self.btn_start.setText(_translate("MainWindow", "启动"))
        self.btn_stop.setText(_translate("MainWindow", "停止"))
        self.groupBox_3.setTitle(_translate("MainWindow", "设置"))
        self.groupBox1.setTitle(_translate("MainWindow", "站点信息"))
        self.label.setText(_translate("MainWindow", "设备编号"))
        self.label_2.setText(_translate("MainWindow", "设备名称"))
        self.groupBox2.setTitle(_translate("MainWindow", "自动运行"))
        self.cb_start.setText(_translate("MainWindow", "自动启动"))
        self.cb_stop.setText(_translate("MainWindow", "自动停止"))
        self.groupBox3.setTitle(_translate("MainWindow", "车流量设置"))
        self.label_3.setText(_translate("MainWindow", "上传模块"))
        self.label_9.setText(_translate("MainWindow", "统计间隔"))
        self.groupBox4.setTitle(_translate("MainWindow", "读取/保存"))
        self.label_5.setText(_translate("MainWindow", "视频来源"))
        self.btn_video.setText(_translate("MainWindow", "选择..."))
        self.label_12.setText(_translate("MainWindow", "本地保存目录"))
        self.btn_save.setText(_translate("MainWindow", "选择..."))
        self.groupBox5.setTitle(_translate("MainWindow", "黑烟设置"))
        self.label_4.setText(_translate("MainWindow", "林格曼黑度阈值"))
        self.label_11.setText(_translate("MainWindow", "上传模块"))
        self.groupBox6.setTitle(_translate("MainWindow", "车道边界设置"))
        self.btn_border.setText(_translate("MainWindow", "设置..."))
        self.groupBox7.setTitle(_translate("MainWindow", "操作"))
        self.btn_update.setText(_translate("MainWindow", "保存"))
        self.btn_add.setText(_translate("MainWindow", "添加"))
        self.btn_delete.setText(_translate("MainWindow", "删除"))
        self.groupBox_2.setTitle(_translate("MainWindow", "日志"))

