# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(717, 598)
        Form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.data_test = QtWidgets.QGroupBox(Form)
        self.data_test.setGeometry(QtCore.QRect(20, 80, 511, 451))
        self.data_test.setObjectName("data_test")
        self.select_need_test = QtWidgets.QGroupBox(Form)
        self.select_need_test.setGeometry(QtCore.QRect(540, 160, 171, 251))
        self.select_need_test.setObjectName("select_need_test")
        self.airday = QtWidgets.QRadioButton(self.select_need_test)
        self.airday.setGeometry(QtCore.QRect(30, 60, 131, 16))
        self.airday.setObjectName("airday")
        self.airmonth = QtWidgets.QRadioButton(self.select_need_test)
        self.airmonth.setGeometry(QtCore.QRect(30, 90, 111, 16))
        self.airmonth.setObjectName("airmonth")
        self.airyear = QtWidgets.QRadioButton(self.select_need_test)
        self.airyear.setGeometry(QtCore.QRect(30, 120, 101, 16))
        self.airyear.setObjectName("airyear")
        self.telemetryday = QtWidgets.QRadioButton(self.select_need_test)
        self.telemetryday.setGeometry(QtCore.QRect(30, 160, 91, 20))
        self.telemetryday.setObjectName("telemetryday")
        self.telemetrymonth = QtWidgets.QRadioButton(self.select_need_test)
        self.telemetrymonth.setGeometry(QtCore.QRect(30, 190, 89, 16))
        self.telemetrymonth.setObjectName("telemetrymonth")
        self.yaoce_data = QtWidgets.QRadioButton(self.select_need_test)
        self.yaoce_data.setGeometry(QtCore.QRect(30, 220, 89, 16))
        self.yaoce_data.setObjectName("yaoce_data")
        self.air_data = QtWidgets.QRadioButton(self.select_need_test)
        self.air_data.setGeometry(QtCore.QRect(30, 30, 101, 16))
        self.air_data.setObjectName("air_data")
        self.gas_value = QtWidgets.QGroupBox(Form)
        self.gas_value.setGeometry(QtCore.QRect(280, 10, 251, 71))
        self.gas_value.setObjectName("gas_value")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gas_value)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.co = QtWidgets.QLabel(self.gas_value)
        self.co.setObjectName("co")
        self.horizontalLayout.addWidget(self.co)
        self.lineEdit = QtWidgets.QLineEdit(self.gas_value)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.hc = QtWidgets.QLabel(self.gas_value)
        self.hc.setObjectName("hc")
        self.horizontalLayout.addWidget(self.hc)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gas_value)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.label = QtWidgets.QLabel(self.gas_value)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gas_value)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.label_2 = QtWidgets.QLabel(self.gas_value)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gas_value)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(540, 10, 171, 101))
        self.groupBox.setObjectName("groupBox")
        self.site = QtWidgets.QComboBox(self.groupBox)
        self.site.setGeometry(QtCore.QRect(30, 60, 111, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site.sizePolicy().hasHeightForWidth())
        self.site.setSizePolicy(sizePolicy)
        self.site.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.site.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.site.setObjectName("site")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(40, 20, 94, 16))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.guangzhou = QtWidgets.QRadioButton(self.splitter)
        self.guangzhou.setObjectName("guangzhou")
        self.qingyuan = QtWidgets.QRadioButton(self.splitter)
        self.qingyuan.setObjectName("qingyuan")
        self.light = QtWidgets.QPushButton(Form)
        self.light.setGeometry(QtCore.QRect(200, 50, 75, 23))
        self.light.setObjectName("light")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 121, 48))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wenzi = QtWidgets.QRadioButton(self.groupBox_2)
        self.wenzi.setChecked(True)
        self.wenzi.setObjectName("wenzi")
        self.horizontalLayout_2.addWidget(self.wenzi)
        self.tuxiang = QtWidgets.QRadioButton(self.groupBox_2)
        self.tuxiang.setObjectName("tuxiang")
        self.horizontalLayout_2.addWidget(self.tuxiang)
        self.jigui = QtWidgets.QPushButton(Form)
        self.jigui.setEnabled(False)
        self.jigui.setGeometry(QtCore.QRect(200, 20, 75, 23))
        self.jigui.setMouseTracking(False)
        self.jigui.setTabletTracking(False)
        self.jigui.setAcceptDrops(False)
        self.jigui.setCheckable(False)
        self.jigui.setChecked(False)
        self.jigui.setDefault(False)
        self.jigui.setFlat(False)
        self.jigui.setObjectName("jigui")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(590, 120, 71, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.data_test.setTitle(_translate("Form", "查询的结果"))
        self.select_need_test.setTitle(_translate("Form", "选择需要测试的数据"))
        self.airday.setText(_translate("Form", "空气质量日统计"))
        self.airmonth.setText(_translate("Form", "空气质量月统计"))
        self.airyear.setText(_translate("Form", "空气质量年统计"))
        self.telemetryday.setText(_translate("Form", "遥测日统计"))
        self.telemetrymonth.setText(_translate("Form", "遥测月统计"))
        self.yaoce_data.setText(_translate("Form", "遥测数据"))
        self.air_data.setText(_translate("Form", "空气质量数据"))
        self.gas_value.setTitle(_translate("Form", "检测气体值"))
        self.co.setText(_translate("Form", "CO"))
        self.hc.setText(_translate("Form", "HC"))
        self.label.setText(_translate("Form", "NO"))
        self.label_2.setText(_translate("Form", "Smoke"))
        self.groupBox.setTitle(_translate("Form", "平台"))
        self.guangzhou.setText(_translate("Form", "广州"))
        self.qingyuan.setText(_translate("Form", "清远"))
        self.light.setText(_translate("Form", "查看光强"))
        self.groupBox_2.setTitle(_translate("Form", "查询模式"))
        self.wenzi.setText(_translate("Form", "文字"))
        self.tuxiang.setText(_translate("Form", "图像"))
        self.jigui.setText(_translate("Form", "查看机柜"))
        self.pushButton.setText(_translate("Form", "查询"))

