
package cn.itcast.mobile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Webservice", targetNamespace = "http://webservice.shengwei.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Webservice {


    /**
     * 
     * @param dwycxxb
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addDwycxxb(
        @WebParam(name = "dwycxxb", partName = "dwycxxb")
        Dwycxxb dwycxxb);

    /**
     * 
     * @param dwhjkqzljlb
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addDwhjkqzljlb(
        @WebParam(name = "dwhjkqzljlb", partName = "dwhjkqzljlb")
        Dwhjkqzljlb dwhjkqzljlb);

    /**
     * 
     * @param jcsbxx
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean updatejcsbxx(
        @WebParam(name = "jcsbxx", partName = "jcsbxx")
        Jcsbxx jcsbxx);

    /**
     * 
     * @param dwxxb
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addDwxxb(
        @WebParam(name = "dwxxb", partName = "dwxxb")
        Dwxxb dwxxb);

    /**
     * 
     * @param cxfFile
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean uploadVide(
        @WebParam(name = "cxfFile", partName = "cxfFile")
        CxfFileWrapper cxfFile);

    /**
     * 
     * @param clsjxxb
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addClsjxxb(
        @WebParam(name = "clsjxxb", partName = "clsjxxb")
        Clsjxxb clsjxxb);

    /**
     * 
     * @param image
     * @param filename
     * @param filePath
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean uploadImage(
        @WebParam(name = "filePath", partName = "filePath")
        String filePath,
        @WebParam(name = "filename", partName = "filename")
        String filename,
        @WebParam(name = "image", partName = "image")
        String image);

    /**
     * 
     * @param ycsbjtjcgcsj
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addYcsbjtjcgcsj(
        @WebParam(name = "ycsbjtjcgcsj", partName = "ycsbjtjcgcsj")
        Ycsbjtjcgcsj ycsbjtjcgcsj);

    /**
     * 
     * @param ycsbzjxxb
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addYcsbzjxxb(
        @WebParam(name = "ycsbzjxxb", partName = "ycsbzjxxb")
        Ycsbzjxxb ycsbzjxxb);

    /**
     * 
     * @param glmhd
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addglmhd(
        @WebParam(name = "glmhd", partName = "glmhd")
        Glmhd glmhd);

    /**
     * 
     * @param ycsbzjgcsj
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addYcsbzjgcsj(
        @WebParam(name = "ycsbzjgcsj", partName = "ycsbzjgcsj")
        Ycsbzjgcsj ycsbzjgcsj);

    /**
     * 
     * @param arg2
     * @param filename
     * @param filePath
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean uploadSP(
        @WebParam(name = "filePath", partName = "filePath")
        String filePath,
        @WebParam(name = "filename", partName = "filename")
        String filename,
        @WebParam(name = "arg2", partName = "arg2")
        byte[] arg2);

    /**
     * 
     * @param ygjcsjxxb
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addYgjcsjxxb(
        @WebParam(name = "ygjcsjxxb", partName = "ygjcsjxxb")
        Ygjcsjxxb ygjcsjxxb);

    /**
     * 
     * @param ydsdwyxjlb
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addYdsdwyxjlb(
        @WebParam(name = "ydsdwyxjlb", partName = "ydsdwyxjlb")
        Ydsdwyxjlb ydsdwyxjlb);

    /**
     * 
     * @param ycsbjcxxb
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addYcsbjcxxb(
        @WebParam(name = "ycsbjcxxb", partName = "ycsbjcxxb")
        Ycsbjcxxb ycsbjcxxb);

}
