# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sfe_smoke.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1502, 990)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_13.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setMinimumSize(QtCore.QSize(0, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_7.setPalette(palette)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setLineWidth(0)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setIndent(0)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_13.addWidget(self.label_7)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setMinimumSize(QtCore.QSize(0, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_11.setPalette(palette)
        self.label_11.setAutoFillBackground(True)
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setLineWidth(0)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setIndent(0)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setMinimumSize(QtCore.QSize(0, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_15.setPalette(palette)
        self.label_15.setAutoFillBackground(True)
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_15.setLineWidth(0)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setIndent(0)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setMinimumSize(QtCore.QSize(0, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_12.setPalette(palette)
        self.label_12.setAutoFillBackground(True)
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_12.setLineWidth(0)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setIndent(0)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setMinimumSize(QtCore.QSize(0, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_13.setPalette(palette)
        self.label_13.setAutoFillBackground(True)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_13.setLineWidth(0)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setIndent(0)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setMinimumSize(QtCore.QSize(0, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_14.setPalette(palette)
        self.label_14.setAutoFillBackground(True)
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_14.setLineWidth(0)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setIndent(0)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelMain = QtWidgets.QLabel(self.groupBox)
        self.labelMain.setMinimumSize(QtCore.QSize(800, 600))
        self.labelMain.setMaximumSize(QtCore.QSize(800, 600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.labelMain.setPalette(palette)
        self.labelMain.setAutoFillBackground(True)
        self.labelMain.setFrameShape(QtWidgets.QFrame.Box)
        self.labelMain.setText("")
        self.labelMain.setObjectName("labelMain")
        self.verticalLayout_8.addWidget(self.labelMain)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.horizontalLayout_24.addLayout(self.verticalLayout_9)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStop = QtWidgets.QPushButton(self.groupBox_3)
        self.btnStop.setAutoDefault(False)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.btnStart = QtWidgets.QPushButton(self.groupBox_3)
        self.btnStart.setDefault(True)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.verticalLayout_13.addWidget(self.groupBox_3)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.checkBoxSave = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxSave.setCheckable(True)
        self.checkBoxSave.setObjectName("checkBoxSave")
        self.verticalLayout_12.addWidget(self.checkBoxSave)
        self.checkBoxSmoke = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxSmoke.setObjectName("checkBoxSmoke")
        self.verticalLayout_12.addWidget(self.checkBoxSmoke)
        self.checkBoxCar = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxCar.setObjectName("checkBoxCar")
        self.verticalLayout_12.addWidget(self.checkBoxCar)
        self.horizontalLayout_20.addWidget(self.groupBox_4)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioVideo = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioVideo.setChecked(True)
        self.radioVideo.setObjectName("radioVideo")
        self.horizontalLayout_8.addWidget(self.radioVideo)
        self.radioStream = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioStream.setObjectName("radioStream")
        self.horizontalLayout_8.addWidget(self.radioStream)
        self.verticalLayout_11.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_9.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.editPath = QtWidgets.QLineEdit(self.groupBox_6)
        self.editPath.setReadOnly(False)
        self.editPath.setObjectName("editPath")
        self.horizontalLayout_9.addWidget(self.editPath)
        self.btnOpen = QtWidgets.QPushButton(self.groupBox_6)
        self.btnOpen.setAutoDefault(False)
        self.btnOpen.setDefault(False)
        self.btnOpen.setFlat(False)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout_9.addWidget(self.btnOpen)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_6)
        self.horizontalLayout_20.addLayout(self.verticalLayout_11)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_16.setTextFormat(QtCore.Qt.PlainText)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.editIP = QtWidgets.QLineEdit(self.groupBox_7)
        self.editIP.setMinimumSize(QtCore.QSize(0, 0))
        self.editIP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editIP.setObjectName("editIP")
        self.horizontalLayout_15.addWidget(self.editIP)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_7)
        self.label_17.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.editPort = QtWidgets.QLineEdit(self.groupBox_7)
        self.editPort.setMaximumSize(QtCore.QSize(50, 16777215))
        self.editPort.setObjectName("editPort")
        self.horizontalLayout_16.addWidget(self.editPort)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.editChannel = QtWidgets.QLineEdit(self.groupBox_7)
        self.editChannel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.editChannel.setObjectName("editChannel")
        self.horizontalLayout_16.addWidget(self.editChannel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.editUser = QtWidgets.QLineEdit(self.groupBox_7)
        self.editUser.setMinimumSize(QtCore.QSize(0, 0))
        self.editUser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editUser.setObjectName("editUser")
        self.horizontalLayout_18.addWidget(self.editUser)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_19.setTextFormat(QtCore.Qt.PlainText)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.editPwd = QtWidgets.QLineEdit(self.groupBox_7)
        self.editPwd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPwd.setObjectName("editPwd")
        self.horizontalLayout_17.addWidget(self.editPwd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.verticalLayout_13.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.label_23 = QtWidgets.QLabel(self.groupBox_8)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_12.addWidget(self.label_25)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.label_22 = QtWidgets.QLabel(self.groupBox_8)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_12.addWidget(self.label_22)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(self.groupBox_8)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_12.addWidget(self.label)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.sliderLevel = QtWidgets.QSlider(self.groupBox_8)
        self.sliderLevel.setMaximum(5)
        self.sliderLevel.setPageStep(1)
        self.sliderLevel.setProperty("value", 2)
        self.sliderLevel.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLevel.setInvertedAppearance(False)
        self.sliderLevel.setInvertedControls(False)
        self.sliderLevel.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sliderLevel.setTickInterval(1)
        self.sliderLevel.setObjectName("sliderLevel")
        self.verticalLayout_7.addWidget(self.sliderLevel)
        self.verticalLayout_13.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBoxAutoStop = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBoxAutoStop.setObjectName("checkBoxAutoStop")
        self.horizontalLayout_11.addWidget(self.checkBoxAutoStop)
        self.timeEditStop = QtWidgets.QTimeEdit(self.groupBox_9)
        self.timeEditStop.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEditStop.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEditStop.setCalendarPopup(False)
        self.timeEditStop.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEditStop.setTime(QtCore.QTime(0, 0, 0))
        self.timeEditStop.setObjectName("timeEditStop")
        self.horizontalLayout_11.addWidget(self.timeEditStop)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBoxAutoStart = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBoxAutoStart.setObjectName("checkBoxAutoStart")
        self.horizontalLayout_10.addWidget(self.checkBoxAutoStart)
        self.timeEditStart = QtWidgets.QTimeEdit(self.groupBox_9)
        self.timeEditStart.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEditStart.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEditStart.setCalendarPopup(False)
        self.timeEditStart.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEditStart.setTime(QtCore.QTime(0, 0, 0))
        self.timeEditStart.setObjectName("timeEditStart")
        self.horizontalLayout_10.addWidget(self.timeEditStart)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.verticalLayout_13.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.editSave = QtWidgets.QLineEdit(self.groupBox_10)
        self.editSave.setReadOnly(False)
        self.editSave.setObjectName("editSave")
        self.horizontalLayout_19.addWidget(self.editSave)
        self.btnSave = QtWidgets.QPushButton(self.groupBox_10)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_19.addWidget(self.btnSave)
        self.verticalLayout_13.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnBorder = QtWidgets.QPushButton(self.groupBox_11)
        self.btnBorder.setObjectName("btnBorder")
        self.verticalLayout.addWidget(self.btnBorder)
        self.verticalLayout_13.addWidget(self.groupBox_11)
        self.horizontalLayout_23.addLayout(self.verticalLayout_13)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.groupBox_12)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSortIndicatorShown(False)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableView)
        self.verticalLayout_6.addWidget(self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setFlat(False)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableHistory = QtWidgets.QTableView(self.groupBox_13)
        self.tableHistory.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableHistory.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableHistory.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableHistory.setObjectName("tableHistory")
        self.verticalLayout_4.addWidget(self.tableHistory)
        self.verticalLayout_6.addWidget(self.groupBox_13)
        self.horizontalLayout_23.addLayout(self.verticalLayout_6)
        self.horizontalLayout_23.setStretch(1, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24.addLayout(self.verticalLayout_15)
        self.verticalLayout_14.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelImg1 = QtWidgets.QLabel(self.groupBox_14)
        self.labelImg1.setMinimumSize(QtCore.QSize(320, 240))
        self.labelImg1.setMaximumSize(QtCore.QSize(320, 240))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.labelImg1.setPalette(palette)
        self.labelImg1.setAutoFillBackground(True)
        self.labelImg1.setFrameShape(QtWidgets.QFrame.Box)
        self.labelImg1.setText("")
        self.labelImg1.setObjectName("labelImg1")
        self.horizontalLayout_2.addWidget(self.labelImg1)
        self.labelImg2 = QtWidgets.QLabel(self.groupBox_14)
        self.labelImg2.setMinimumSize(QtCore.QSize(320, 240))
        self.labelImg2.setMaximumSize(QtCore.QSize(320, 240))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.labelImg2.setPalette(palette)
        self.labelImg2.setAutoFillBackground(True)
        self.labelImg2.setFrameShape(QtWidgets.QFrame.Box)
        self.labelImg2.setText("")
        self.labelImg2.setObjectName("labelImg2")
        self.horizontalLayout_2.addWidget(self.labelImg2)
        self.labelBack = QtWidgets.QLabel(self.groupBox_14)
        self.labelBack.setMinimumSize(QtCore.QSize(320, 240))
        self.labelBack.setMaximumSize(QtCore.QSize(320, 240))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.labelBack.setPalette(palette)
        self.labelBack.setAutoFillBackground(True)
        self.labelBack.setFrameShape(QtWidgets.QFrame.Box)
        self.labelBack.setText("")
        self.labelBack.setObjectName("labelBack")
        self.horizontalLayout_2.addWidget(self.labelBack)
        self.horizontalLayout_33.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.labelSId = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelSId.setFont(font)
        self.labelSId.setText("")
        self.labelSId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSId.setObjectName("labelSId")
        self.horizontalLayout_3.addWidget(self.labelSId)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.labelId = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelId.setFont(font)
        self.labelId.setText("")
        self.labelId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelId.setObjectName("labelId")
        self.horizontalLayout_6.addWidget(self.labelId)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_6 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_21.addWidget(self.label_6)
        self.labelTime = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTime.setFont(font)
        self.labelTime.setText("")
        self.labelTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTime.setObjectName("labelTime")
        self.horizontalLayout_21.addWidget(self.labelTime)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.labelLine = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelLine.setFont(font)
        self.labelLine.setText("")
        self.labelLine.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLine.setObjectName("labelLine")
        self.horizontalLayout_4.addWidget(self.labelLine)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.labelRingelmann = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelRingelmann.setFont(font)
        self.labelRingelmann.setText("")
        self.labelRingelmann.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRingelmann.setObjectName("labelRingelmann")
        self.horizontalLayout_5.addWidget(self.labelRingelmann)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.labelPlate = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPlate.setFont(font)
        self.labelPlate.setText("")
        self.labelPlate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPlate.setObjectName("labelPlate")
        self.horizontalLayout_7.addWidget(self.labelPlate)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_24 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_27.addWidget(self.label_24)
        self.labelPColor = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPColor.setFont(font)
        self.labelPColor.setText("")
        self.labelPColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPColor.setObjectName("labelPColor")
        self.horizontalLayout_27.addWidget(self.labelPColor)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_27)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_26 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_22.addWidget(self.label_26)
        self.labelCarType = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelCarType.setFont(font)
        self.labelCarType.setText("")
        self.labelCarType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCarType.setObjectName("labelCarType")
        self.horizontalLayout_22.addWidget(self.labelCarType)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_27 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_30.addWidget(self.label_27)
        self.labelCarColor = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelCarColor.setFont(font)
        self.labelCarColor.setText("")
        self.labelCarColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCarColor.setObjectName("labelCarColor")
        self.horizontalLayout_30.addWidget(self.labelCarColor)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_30)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_33.addWidget(self.groupBox_15)
        self.verticalLayout_14.addLayout(self.horizontalLayout_33)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "林格曼黑度标准色卡"))
        self.label_7.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "1"))
        self.label_15.setText(_translate("MainWindow", "2"))
        self.label_12.setText(_translate("MainWindow", "3"))
        self.label_13.setText(_translate("MainWindow", "4"))
        self.label_14.setText(_translate("MainWindow", "5"))
        self.groupBox.setTitle(_translate("MainWindow", "主视图"))
        self.groupBox_3.setTitle(_translate("MainWindow", "检测控制"))
        self.btnStop.setText(_translate("MainWindow", "停止"))
        self.btnStart.setText(_translate("MainWindow", "开始"))
        self.groupBox_4.setTitle(_translate("MainWindow", "播放设置"))
        self.checkBoxSave.setText(_translate("MainWindow", "保存黑烟视频"))
        self.checkBoxSmoke.setText(_translate("MainWindow", "标出黑烟"))
        self.checkBoxCar.setText(_translate("MainWindow", "标出汽车"))
        self.groupBox_5.setTitle(_translate("MainWindow", "视频模式"))
        self.radioVideo.setText(_translate("MainWindow", "视频文件"))
        self.radioStream.setText(_translate("MainWindow", "视频流"))
        self.groupBox_6.setTitle(_translate("MainWindow", "视频文件设置"))
        self.btnOpen.setText(_translate("MainWindow", "选择..."))
        self.groupBox_7.setTitle(_translate("MainWindow", "视频流设置"))
        self.label_16.setText(_translate("MainWindow", "地  址"))
        self.label_17.setText(_translate("MainWindow", "端口号"))
        self.label_21.setText(_translate("MainWindow", "通道号"))
        self.label_18.setText(_translate("MainWindow", "用户名"))
        self.label_19.setText(_translate("MainWindow", "密  码"))
        self.groupBox_8.setTitle(_translate("MainWindow", "林格曼黑度阈值"))
        self.label_5.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "1"))
        self.label_23.setText(_translate("MainWindow", "2"))
        self.label_25.setText(_translate("MainWindow", "3"))
        self.label_22.setText(_translate("MainWindow", "4"))
        self.label.setText(_translate("MainWindow", "5"))
        self.groupBox_9.setTitle(_translate("MainWindow", "自动任务"))
        self.checkBoxAutoStop.setText(_translate("MainWindow", "自动停止"))
        self.timeEditStop.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.checkBoxAutoStart.setText(_translate("MainWindow", "自动开始"))
        self.timeEditStart.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.groupBox_10.setTitle(_translate("MainWindow", "保存目录"))
        self.btnSave.setText(_translate("MainWindow", "打开保存目录"))
        self.groupBox_11.setTitle(_translate("MainWindow", "车道设置"))
        self.btnBorder.setText(_translate("MainWindow", "设置..."))
        self.groupBox_12.setTitle(_translate("MainWindow", "检测结果"))
        self.groupBox_13.setTitle(_translate("MainWindow", "历史记录"))
        self.groupBox_14.setTitle(_translate("MainWindow", "抓拍图片 && 抓拍视频"))
        self.groupBox_15.setTitle(_translate("MainWindow", "记录信息"))
        self.label_3.setText(_translate("MainWindow", "站点名称"))
        self.label_4.setText(_translate("MainWindow", "记录编号"))
        self.label_6.setText(_translate("MainWindow", "通过时间"))
        self.label_8.setText(_translate("MainWindow", "车道号"))
        self.label_10.setText(_translate("MainWindow", "林格曼黑度"))
        self.label_9.setText(_translate("MainWindow", "车牌"))
        self.label_24.setText(_translate("MainWindow", "车牌颜色"))
        self.label_26.setText(_translate("MainWindow", "车型"))
        self.label_27.setText(_translate("MainWindow", "车身颜色"))

