# Generated by Django 2.1.7 on 2019-03-28 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190328_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 6, 39, 17, 301052, tzinfo=utc)),
        ),
    ]
