# Generated by Django 2.1.7 on 2019-04-06 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190406_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 14, 17, 24, 555695, tzinfo=utc)),
        ),
    ]
